### PR TITLE
Fix assertion failure after upgrading to Xcode 6+

### PR DESCRIPTION
**Pull request by kentwelcome**
By reversing the Core Graphics framework, the function CGS_REQUIRE_INIT will checking an internal variable "did_initialize".
And the value of "did_initialize" will be set in function "CGSInitialize"

### CODE REVIEW

**Comment by Simon-Kaz** [comment]
Hey @kentwelcome would you be able to share your fork until this is merged?

**Comment by kentwelcome** [comment]
@Simon-Kaz : Sure, you could access my fork by following link.
https://github.com/kentwelcome/screen_recording

**Comment by Simon-Kaz** [comment]
Confirmed working, thanks :)

**Comment by bootstraponline** [comment]
Awesome. Thanks for the fix.

**Pull request merged**
